export const fonts = [
  "Abadi MT Condensed Light",
  "Aharoni",
  "Aharoni Bold",
  "Aldhabi",
  "AlternateGothic2 BT",
  "Andale Mono",
  "Andalus",
  "Angsana New",
  "AngsanaUPC",
  "Aparajita",
  "Apple Chancery",
  "Arabic Typesetting",
  "Arial",
  "Arial Black",
  "Arial Nova",
  "Arial Rounded MT Bold",
  "Arial narrow",
  "Arnoldboecklin",
  "Avanta Garde",
  "BIZ UDGothic",
  "BIZ UDMincho Medium",
  "Bahnschrift",
  "Bahnschrift Light",
  "Bahnschrift SemiBold",
  "Bahnschrift SemiLight",
  "Baskerville",
  "Batang",
  "BatangChe",
  "Big Caslon",
  "Blippo",
  "Bodoni MT",
  "Book Antiqua",
  "Bookman",
  "Bradley Hand",
  "Browallia New",
  "BrowalliaUPC",
  "Brush Script MT",
  "Brush Script Std",
  "Brushstroke",
  "Calibri",
  "Calibri Light",
  "Calisto MT",
  "Cambodian",
  "Cambria",
  "Cambria Math",
  "Candara",
  "Century Gothic",
  "Chalkduster",
  "Cherokee",
  "Comic Sans",
  "Comic Sans MS",
  "Consolas",
  "Constantia",
  "Copperplate",
  "Copperplate Gothic Bold",
  "Copperplate Gothic Light",
  "Corbel",
  "Cordia New",
  "CordiaUPC",
  "Coronet script",
  "Coronetscript",
  "Courier",
  "Courier New",
  "DFKai-SB",
  "DaunPenh",
  "David",
  "DengXian",
  "Didot",
  "DilleniaUPC",
  "DokChampa",
  "Dotum",
  "DotumChe",
  "Ebrima",
  "Estrangelo Edessa",
  "EucrosiaUPC",
  "Euphemia",
  "FangSong",
  "Florence",
  "FrankRuehl",
  "Franklin Gothic Medium",
  "FreesiaUPC",
  "Futara",
  "Gabriola",
  "Gadugi",
  "Garamond",
  "Gautami",
  "Geneva",
  "Georgia",
  "Georgia Pro",
  "Gill Sans",
  "Gill Sans Nova",
  "Gisha",
  "Goudy Old Style",
  "Gulim",
  "GulimChe",
  "Gungsuh",
  "GungsuhChe",
  "Hebrew",
  "Helvetica",
  "Hoefler Text",
  "HoloLens MDL2 Assets",
  "Impact",
  "Ink Free",
  "IrisUPC",
  "Iskoola Pota",
  "Japanese",
  "JasmineUPC",
  "Javanese Text",
  "Jazz LET",
  "KaiTi",
  "Kalinga",
  "Kartika",
  "Khmer UI",
  "KodchiangUPC",
  "Kokila",
  "Korean",
  "Lao",
  "Lao UI",
  "Latha",
  "Leelawadee",
  "Leelawadee UI",
  "Leelawadee UI Semilight",
  "Levenim MT",
  "LilyUPC",
  "Lucida Bright",
  "Lucida Console",
  "Lucida Handwriting",
  "Lucida Sans",
  "Lucida Sans Typewriter",
  "Lucida Sans Unicode",
  "Lucidatypewriter",
  "Luminari",
  "MS Gothic",
  "MS Mincho",
  "MS PGothic",
  "MS PMincho",
  "MS UI Gothic",
  "MV Boli",
  "Malgun Gothic",
  "Malgun Gothic Semilight",
  "Mangal",
  "Marker Felt",
  "Marlett",
  "Meiryo",
  "Meiryo UI",
  "Microsoft Himalaya",
  "Microsoft JhengHei",
  "Microsoft JhengHei UI",
  "Microsoft New Tai Lue",
  "Microsoft PhagsPa",
  "Microsoft Sans Serif",
  "Microsoft Tai Le",
  "Microsoft Uighur",
  "Microsoft YaHei",
  "Microsoft YaHei UI",
  "Microsoft Yi Baiti",
  "MingLiU",
  "MingLiU-ExtB",
  "MingLiU_HKSCS",
  "MingLiU_HKSCS-ExtB",
  "Miriam",
  "Monaco",
  "Mongolian Baiti",
  "MoolBoran",
  "Myanmar Text",
  "NSimSun",
  "Narkisim",
  "Neue Haas Grotesk Text Pro",
  "New Century Schoolbook",
  "News Gothic MT",
  "Nirmala UI",
  "Noto",
  "Nyala",
  "Oldtown",
  "Optima",
  "PMingLiU",
  "Palatino",
  "Palatino Linotype",
  "Papyrus",
  "Parkavenue",
  "Perpetua",
  "Plantagenet Cherokee",
  "Raavi",
  "Rockwell",
  "Rockwell Extra Bold",
  "Rockwell Nova",
  "Rockwell Nova Cond",
  "Rockwell Nova Extra Bold",
  "Rod",
  "Sakkal Majalla",
  "Sanskrit Text",
  "Segoe MDL2 Assets",
  "Segoe Print",
  "Segoe Script",
  "Segoe UI",
  "Segoe UI Emoji",
  "Segoe UI Historic",
  "Segoe UI Symbol",
  "Shonar Bangla",
  "Shruti",
  "SimHei",
  "SimKai",
  "SimSun",
  "SimSun-ExtB",
  "Simplified Arabic",
  "Simplified Chinese",
  "Sitka",
  "Snell Roundhan",
  "Stencil Std",
  "Sylfaen",
  "Symbol",
  "Tahoma",
  "Thai",
  "Times New Roman",
  "Traditional Arabic",
  "Traditional Chinese",
  "Trattatello",
  "Trebuchet MS",
  "Tunga",
  "UD Digi KyoKasho N-R",
  "UD Digi KyoKasho NK-R",
  "UD Digi KyoKasho NP-R",
  "UD Digi Kyokasho",
  "URW Chancery",
  "Urdu Typesetting",
  "Utsaah",
  "Vani",
  "Verdana",
  "Verdana Pro",
  "Vijaya",
  "Vrinda",
  "Webdings",
  "Westminster",
  "Wingdings",
  "Yu Gothic",
  "Yu Gothic UI",
  "Yu Mincho",
  "Zapf Chancery"
] as const satisfies string[];

export type FontFamily = (typeof fonts)[number];
